In [10]:
import pandas as pd

data = pd.read_csv("ACSDP5Y2020.DP05-Data (2).csv")
data.head(5)

C:\Users\Student\AppData\Local\Temp\ipykernel_21976\2037184116.py:3: DtypeWarning: Columns (2,3,4,5,6,7,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,58,59,60,61,62,63,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,228,236,244,304,318,352) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("ACSDP5Y2020.DP05-Data (2).csv")

,GEO_ID,NAME,DP05_0001E,DP05_0001M,DP05_0002E,DP05_0002M,DP05_0003E,DP05_0003M,DP05_0004E,DP05_0004M,...,DP05_0085PM,DP05_0086PE,DP05_0086PM,DP05_0087PE,DP05_0087PM,DP05_0088PE,DP05_0088PM,DP05_0089PE,DP05_0089PM,Unnamed: 358
0,Geography,Geographic Area Name,Estimate!!SEX AND AGE!!Total population,Margin of Error!!SEX AND AGE!!Total population,Estimate!!SEX AND AGE!!Total population!!Male,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Female,Margin of Error!!SEX AND AGE!!Total population...,Estimate!!SEX AND AGE!!Total population!!Sex r...,Margin of Error!!SEX AND AGE!!Total population...,...,Percent Margin of Error!!HISPANIC OR LATINO AN...,Percent!!Total housing units,Percent Margin of Error!!Total housing units,"Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...","Percent!!CITIZEN, VOTING AGE POPULATION!!Citiz...","Percent Margin of Error!!CITIZEN, VOTING AGE P...",NaN
1,0400000US06,California,39346023,*****,19562882,1263,19783141,1263,98.9,0.1,...,0.1,(X),(X),25774911,(X),49.1,0.1,50.9,0.1,NaN
2,1400000US06001400100,"Census Tract 4001, Alameda County, California",3035,402,1562,323,1473,158,106.0,21.4,...,3.6,(X),(X),2217,(X),49.8,4.0,50.2,4.0,NaN
3,1400000US06001400200,"Census Tract 4002, Alameda County, California",1983,209,996,130,987,122,100.9,14.5,...,5.0,(X),(X),1588,(X),49.7,3.7,50.3,3.7,NaN
4,1400000US06001400300,"Census Tract 4003, Alameda County, California",5058,559,2441,373,2617,394,93.3,19.4,...,3.7,(X),(X),3919,(X),46.6,6.0,53.4,6.0,NaN

In [11]:
# Load the dataset
data = pd.read_csv("ACSDP5Y2020.DP05-Data (2).csv")

# Print the "Name" column
print(data['NAME'])

0                                Geographic Area Name
1                                          California
2       Census Tract 4001, Alameda County, California
3       Census Tract 4002, Alameda County, California
4       Census Tract 4003, Alameda County, California
                            ...
9126     Census Tract 409.02, Yuba County, California
9127     Census Tract 410.01, Yuba County, California
9128     Census Tract 410.02, Yuba County, California
9129     Census Tract 411.01, Yuba County, California
9130     Census Tract 411.02, Yuba County, California
Name: NAME, Length: 9131, dtype: object

C:\Users\Student\AppData\Local\Temp\ipykernel_21976\211890816.py:2: DtypeWarning: Columns (2,3,4,5,6,7,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,58,59,60,61,62,63,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,228,236,244,304,318,352) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("ACSDP5Y2020.DP05-Data (2).csv")

In [12]:

# Define the function to convert descriptive labels into FIPS codes with error handling
def convert_to_fips(description):
    try:
        # Extracting the tract number part and handling subdivisions (ignoring decimal subdivisions for simplicity)
        match = re.search(r"Census Tract (\d+)(\.\d+)?,", description)
        if match:
            tract_number = match.group(1)  # This will capture the number before the decimal if present
            # Formatting the FIPS code: State (06) + County (001) + Tract (zero-padded to 6 digits)
            fips_code = f"06001{int(tract_number):06d}"
            return fips_code
        else:
            # Return a default or placeholder if no match is found (adjust as needed)
            return None
    except Exception as e:
        print(f"Error processing description '{description}': {e}")
        return None

# Apply the function to create a new column in the DataFrame
data['FIPS code'] = data['NAME'].apply(convert_to_fips)

# Print the first 5 rows of the DataFrame to verify the new column
print(data[['NAME', 'FIPS code']].head(5))

                                            NAME    FIPS code
0                           Geographic Area Name         None
1                                     California         None
2  Census Tract 4001, Alameda County, California  06001004001
3  Census Tract 4002, Alameda County, California  06001004002
4  Census Tract 4003, Alameda County, California  06001004003

In [13]:
fips_code_length = len(data['FIPS code'])

print(f"The length of the 'FIPS code' column is: {fips_code_length}")

The length of the 'FIPS code' column is: 9131